### ISSUE TITLE
u-boot-at91: unreachable SRC_URI in 2018.07

### ISSUE THREAD

**Issue by gizero** [linux4sam/meta-atmel#110]
The server `SRC_URI` points to in `u-boot-at91_2018.07.bb` does not seem to be publicly available. Was this meant to be `SRC_URI = "git://github.com/linux4sam/u-boot-at91.git;protocol=https;branch=${UBRANCH}"` instead?

Here there seem to be the corresponding branch which I'm giving a test right now...

**Comment by RazvanStef** [comment]
Hello,

Thank you for noticing this issue. A [fix](https://github.com/linux4sam/meta-atmel/commit/2380cc08c13f1ace59b65da3e380fcc398c6af73 ) was committed on the sumo branch.

Best regards,
Razvan
