### ISSUE TITLE
sumo wic generation fail

### ISSUE THREAD

**Issue by fromeijn** [linux4sam/meta-atmel#113]
While trying to build the core-image-minimal for the sama5d3_xplained (sd) i got the following error:

`| DEBUG: Executing shell function do_image_wic
| INFO: Creating image(s)...
| 
| WARNING: bootloader config not specified, using defaults
| 
| ERROR: _exec_cmd: install -m 0644 -D /media/floris/1TB_WD/eoi-datalogger/poky/build/tmp/deploy/images/sama5d3-xplained-sd/sama5d3_xplained.itb /media/floris/1TB_WD/eoi-datalogger/poky/build/tmp/work/sama5d3_xplained_sd-poky-linux-gnueabi/core-image-minimal/1.0-r0/deploy-core-image-minimal-image-complete/core-image-minimal-sama5d3-xplained-sd-20181103164502/tmp.wic.fplzietd/boot.1/sama5d3_xplained.itb returned '1' instead of 0
| output: install: cannot stat '/media/floris/1TB_WD/eoi-datalogger/poky/build/tmp/deploy/images/sama5d3-xplained-sd/sama5d3_xplained.itb': No such file or directory
| 
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_image_wic (log file is located at /media/floris/1TB_WD/eoi-datalogger/poky/build/tmp/work/sama5d3_xplained_sd-poky-linux-gnueabi/core-image-minimal/1.0-r0/temp/log.do_image_wic.3597)
ERROR: Task (/media/floris/1TB_WD/eoi-datalogger/poky/meta/recipes-core/images/core-image-minimal.bb:do_image_wic) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2439 tasks of which 5 didn't need to be rerun and 1 failed.`

probably something got broken, not sure how to fix this
commit 4d4276bb7dda6bb3e943feb2703983318617cfdf

**Comment by texierp** [comment]
Hi,

Indeed, you have to include the dt-overlay-at91 package, you can check the file atmel-demo-image.inc.

Pierre-Jean

**Comment by fromeijn** [comment]
So if i understand correctly, you cant run `bitbake core-image-minimal` anymore? you always need an custom image with `dt-overlay-at91`? so `bitbake atmel-demo-image` should work without a problem?

**Comment by alexandrebelloni** [comment]
I think dt-overlay-at91 should be added in EXTRA_IMAGEDEPENDS from the machine conf. That would solve that issue.
