### ISSUE TITLE
Thud branch

### ISSUE THREAD

**Issue by texierp** [linux4sam/meta-atmel#116]
Hello,

I think it is time to create the thud branch for this BSP :). In fact, this branch is needed for consistency with other layers (e.g meta-mender-community : https://github.com/mendersoftware/meta-mender-community/tree/thud)

Thanks
/PJ

**Comment by RazvanStef** [comment]
Hello,

Thank you for the suggestion.

I've pushed a new [thud](https://github.com/linux4sam/meta-atmel/tree/thud) branch. It is under development as there are some issues with the QT5 support.

This branch can be used to build not-QT5 images, like atmel-demo-image.

Best regards,
Razvan

**Comment by texierp** [comment]
Thanks a lot @RazvanStef
