### ISSUE TITLE
 qtbase patch error on Thud branch

### ISSUE THREAD

**Issue by CleberPeter** [linux4sam/meta-atmel#131]
I get the following errors when apply the patch's from qtbase on Thud branch:

`Applying patch 0004-Provide-access-to-linuxfb-dri-fd-through-platform.patch
patching file src/platformsupport/fbconvenience/qfbscreen_p.h
patching file src/plugins/platforms/linuxfb/qlinuxfbdrmscreen.cpp
patching file src/plugins/platforms/linuxfb/qlinuxfbdrmscreen.h
patching file src/plugins/platforms/linuxfb/qlinuxfbintegration.cpp
Hunk #1 FAILED at 172.
1 out of 1 hunk FAILED -- rejects in file src/plugins/platforms/linuxfb/qlinuxfbintegration.cpp
patching file src/plugins/platforms/linuxfb/qlinuxfbscreen.h
Patch 0004-Provide-access-to-linuxfb-dri-fd-through-platform.patch does not apply (enforce with -f)`

*Using patch's from master branch the error is solved.

meta-qt5: On Thud branch the version of QT is 5.11.

**Comment by texierp** [comment]
Hi @CleberPeter,

Can you check this PR https://github.com/linux4sam/meta-atmel/pull/132

And let me know if it is sufficient for you.

/Pierre-Jean

**Comment by CleberPeter** [comment]
Yes, this solve. 

Thanks.
