### ISSUE TITLE
Cannot see the 4.5" display connected to the SAMA5D27 SOM1-ek board. I am using the linux4sam-poky-sama5d27_som1_ek_video-6.0.img.bz2 image on the SD card. Do I need to rebuild the image? Thank you.

### ISSUE THREAD

**Issue by TMScottSafety** [linux4sam/meta-atmel#139]

**Comment by RazvanStef** [comment]
Hello,

What is the exact model of the display you are using? Can you please provide some bootlogs?

There are also some pages with more info about the PDAs usage:
http://www.at91.com/linux4sam/bin/view/Linux4SAM/ConnectModuleFromPDA
http://www.at91.com/linux4sam/bin/view/Linux4SAM/PDADetectionAtBoot
http://www.at91.com/linux4sam/bin/view/Linux4SAM/SelectingPDAatBoot

Regards,
Razvan

**Comment by TMScottSafety** [comment]
It is A PDA 4.3”
https://www.digikey.com/product-detail/en/precision-design-associates-inc/90-00123-A0/1230-1007-ND/6099992
Thank you.
Traian

**Comment by RazvanStef** [comment]
Hello,

I just tested on SAMA5D27 SOM1-ek  with a TM4301B display, as you suggested. Display works fine with the image downloaded from http://www.at91.com/linux4sam/bin/view/Linux4SAM/Sama5d27Som1EKMainPage#Demo_archives.

Can you see if the display is detected in u-boot?

Regards,
Razvan

**Comment by TMScottSafety** [comment]
Hi Razvan,
The display is blank…
Here is the login Tera Term print out:

RomBOOT


AT91Bootstrap 3.8.11 (Fri Oct 12 06:34:28 EEST 2018)

SD/MMC: Image: Read file u-boot.bin to 0x23f00000
MMC: ADMA supported
SD: Card Capacity: High or Extended
SD: Specification Version 3.0X
SD/MMC: Done to load image
<debug_uart>

U-Boot 2018.07-linux4sam_6.0 (Oct 12 2018 - 06:34:36 +0300)

CPU: SAMA5D27 1G bits DDR2 SDRAM
Crystal frequency:       24 MHz
CPU clock        :      492 MHz
Master clock     :      164 MHz
DRAM:  128 MiB
MMC:   sdio-host@a0000000: 0, sdio-host@b0000000: 1
Loading Environment from FAT... OK
In:    serial@f8020000
Out:   serial@f8020000
Err:   serial@f8020000
Net:   eth0: ethernet@f8008000
Hit any key to stop autoboot:  0
3952756 bytes read in 247 ms (15.3 MiB/s)
## Loading kernel from FIT Image at 21000000 ...
   Using 'kernel_dtb' configuration
   Trying 'kernel@1' kernel subimage
     Description:  Linux4SAM Linux kernel
     Type:         Kernel Image
     Compression:  uncompressed
     Data Start:   0x210000e0
     Data Size:    3887448 Bytes = 3.7 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: 0x22000000
     Entry Point:  0x22000000
     Hash algo:    crc32
     Hash value:   284556d8
     Hash algo:    sha1
     Hash value:   21a2bc6b91b88b6b93507bda6efd0f0653911201
   Verifying Hash Integrity ... crc32+ sha1+ OK
## Loading fdt from FIT Image at 21000000 ...
   Using 'kernel_dtb' configuration
   Trying 'base_fdt' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x213b5364
     Data Size:    44915 Bytes = 43.9 KiB
     Architecture: ARM
     Load Address: 0x23000000
     Hash algo:    crc32
     Hash value:   44aa981a
     Hash algo:    sha1
     Hash value:   96610a3de96b76f7669da56de84f1aac5689c2f4
   Verifying Hash Integrity ... crc32+ sha1+ OK
   Loading fdt from 0x213b5364 to 0x23000000
   Booting using the fdt blob at 0x23000000
   Loading Kernel Image ... OK
   Loading Device Tree to 27b47000, end 27b54f72 ... OK

Starting kernel ...

Booting Linux on physical CPU 0x0
Linux version 4.14.73-linux4sam_6.0 (claudiu@ROB-DK-LAB08) (gcc version 6.4.0 (Buildroot 2018.02)) #1 Fri Oct 12 06:36:21 EEST 2018
CPU: ARMv7 Processor [410fc051] revision 1 (ARMv7), cr=10c53c7d
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
OF: fdt: Machine model: Atmel SAMA5D27 SOM1 EK
Memory policy: Data cache writeback
cma: Reserved 16 MiB at 0x26800000
CPU: All CPU(s) started in SVC mode.
Built 1 zonelists, mobility grouping on.  Total pages: 32480
Kernel command line: console=ttyS0,115200 root=/dev/mmcblk0p2 rw rootwait rootfstype=ext4 atmel.pm_modes=standby,ulp1
PID hash table entries: 512 (order: -1, 2048 bytes)
Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
Memory: 103504K/131072K available (6144K kernel code, 259K rwdata, 1040K rodata, 1024K init, 175K bss, 11184K reserved, 16384K cma-reserved)
Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
    vmalloc : 0xc8800000 - 0xff800000   ( 880 MB)
    lowmem  : 0xc0000000 - 0xc8000000   ( 128 MB)
    modules : 0xbf000000 - 0xc0000000   (  16 MB)
      .text : 0xc0008000 - 0xc0700000   (7136 kB)
      .init : 0xc0900000 - 0xc0a00000   (1024 kB)
      .data : 0xc0a00000 - 0xc0a40f50   ( 260 kB)
       .bss : 0xc0a40f50 - 0xc0a6ce04   ( 176 kB)
NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
L2C-310 ID prefetch enabled, offset 2 lines
L2C-310 dynamic clock gating enabled, standby mode enabled
L2C-310 cache controller enabled, 8 ways, 128 kB
L2C-310: CACHE_ID 0x410000c9, AUX_CTRL 0x36020000
clocksource: pit: mask: 0x7ffffff max_cycles: 0x7ffffff, max_idle_ns: 11654027029 ns
sched_clock: 32 bits at 100 Hz, resolution 10000000ns, wraps every 21474836475000000ns
Console: colour dummy device 80x30
Calibrating delay loop... 326.86 BogoMIPS (lpj=1634304)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
CPU: Testing write buffer coherency: ok
Setting up static identity map for 0x20100000 - 0x20100060
devtmpfs: initialized
random: get_random_u32 called from 0xc032e1b8 with crng_init=0
VFP support v0.3: implementor 41 architecture 2 part 30 variant 5 rev 1
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
futex hash table entries: 256 (order: -1, 3072 bytes)
pinctrl core: initialized pinctrl subsystem
NET: Registered protocol family 16
DMA: preallocated 256 KiB pool for atomic coherent allocations
cpuidle: using governor menu
AT91: PM: standby: standby, suspend: ulp1
clocksource: tcb_clksrc: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 186464433812 ns
at_xdmac f0010000.dma-controller: 16 channels, mapped at 0xc8847000
at_xdmac f0004000.dma-controller: 16 channels, mapped at 0xc8849000
AT91: Detected SoC family: sama5d2
AT91: Detected SoC: sama5d27c 128MiB SiP, revision 2
VDDANA: supplied by VDDIN_3V3
advref: supplied by VDDANA
SCSI subsystem initialized
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
at91_i2c f8028000.i2c: could not find pctldev for node /ahb/apb/pinctrl@fc038000/i2c0_default, deferring probe
at91_i2c fc028000.i2c: could not find pctldev for node /ahb/apb/pinctrl@fc038000/i2c1_default, deferring probe
media: Linux media interface: v0.10
Linux video capture interface: v2.00
pps_core: LinuxPPS API ver. 1 registered
pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
PTP clock support registered
Advanced Linux Sound Architecture Driver Initialized.
clocksource: Switched to clocksource tcb_clksrc
NET: Registered protocol family 2
TCP established hash table entries: 1024 (order: 0, 4096 bytes)
TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
TCP: Hash tables configured (established 1024 bind 1024)
UDP hash table entries: 256 (order: 0, 4096 bytes)
UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
NET: Registered protocol family 1
RPC: Registered named UNIX socket transport module.
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
workingset: timestamp_bits=14 max_order=15 bucket_order=1
io scheduler noop registered (default)
io scheduler mq-deadline registered
io scheduler kyber registered
pinctrl-at91-pio4 fc038000.pinctrl: atmel pinctrl initialized
brd: module loaded
loop: module loaded
atmel_usart_serial.0.auto: ttyS0 at MMIO 0xf8020000 (irq = 37, base_baud = 5125000) is a ATMEL_SERIAL
console [ttyS0] enabled
atmel_usart_serial.1.auto: ttyS2 at MMIO 0xf8024000 (irq = 38, base_baud = 5125000) is a ATMEL_SERIAL
atmel_usart_serial.2.auto: ttyS1 at MMIO 0xfc00c000 (irq = 41, base_baud = 5125000) is a ATMEL_SERIAL
at91_i2c f8038600.i2c: can't get DMA channel, continue without DMA support
at91_i2c f8038600.i2c: Using FIFO (16 data)
at91_i2c f8038600.i2c: AT91 i2c bus driver (hw version: 0x704).
atmel_qspi f0024000.spi: sst26vf064b (8192 Kbytes)
5 ofpart partitions found on MTD device f0024000.spi
Creating 5 MTD partitions on "f0024000.spi":
0x000000000000-0x000000010000 : "at91bootstrap"
0x000000010000-0x0000000b0000 : "bootloader"
0x0000000b0000-0x0000000c0000 : "bootloader env"
0x0000000c0000-0x0000000e0000 : "device tree"
0x0000000e0000-0x0000004e0000 : "kernel"
atmel_spi f8000000.spi: DMA TX channel not available, SPI unable to use DMA
atmel_spi f8000000.spi: Atmel SPI Controller using PIO only
atmel_spi f8000000.spi: Using FIFO (16 data)
atmel_spi f8000000.spi: Atmel SPI Controller version 0x311 at 0xf8000000 (irq 30)
atmel_spi fc018400.spi: DMA TX channel not available, SPI unable to use DMA
atmel_spi fc018400.spi: Atmel SPI Controller using PIO only
atmel_spi fc018400.spi: Using FIFO (16 data)
atmel_spi fc018400.spi: Atmel SPI Controller version 0x311 at 0xfc018400 (irq 180)
libphy: Fixed MDIO Bus: probed
CAN device driver interface
m_can fc050000.can: m_can device registered (irq=49, version=31)
libphy: MACB_mii_bus: probed
Micrel KSZ8081 or KSZ8091 f8008000.ethernet-ffffffff:07: attached PHY driver [Micrel KSZ8081 or KSZ8091] (mii_bus:phy_addr=f8008000.ethernet-ffffffff:07, irq=178)
macb f8008000.ethernet eth0: Cadence GEM rev 0x00020203 at 0xf8008000 irq 31 (54:10:ec:33:96:0c)
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ehci-atmel: EHCI Atmel driver
atmel-ehci 500000.ehci: EHCI Host Controller
atmel-ehci 500000.ehci: new USB bus registered, assigned bus number 1
atmel-ehci 500000.ehci: irq 19, io mem 0x00500000
atmel-ehci 500000.ehci: USB 2.0 started, EHCI 1.00
usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
usb usb1: Product: EHCI Host Controller
usb usb1: Manufacturer: Linux 4.14.73-linux4sam_6.0 ehci_hcd
usb usb1: SerialNumber: 500000.ehci
hub 1-0:1.0: USB hub found
hub 1-0:1.0: 3 ports detected
ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
ohci-atmel: OHCI Atmel driver
at91_ohci 400000.ohci: failed to request gpio "overcurrent" IRQ
at91_ohci 400000.ohci: failed to request gpio "overcurrent" IRQ
at91_ohci 400000.ohci: failed to request gpio "overcurrent" IRQ
at91_ohci 400000.ohci: USB Host Controller
at91_ohci 400000.ohci: new USB bus registered, assigned bus number 2
at91_ohci 400000.ohci: irq 19, io mem 0x00400000
usb usb2: New USB device found, idVendor=1d6b, idProduct=0001
usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
usb usb2: Product: USB Host Controller
usb usb2: Manufacturer: Linux 4.14.73-linux4sam_6.0 ohci_hcd
usb usb2: SerialNumber: at91
hub 2-0:1.0: USB hub found
hub 2-0:1.0: 3 ports detected
usbcore: registered new interface driver usb-storage
rtc rtc0: invalid alarm value: 1900-1-1 0:0:0
at91_rtc f80480b0.rtc: registered as rtc0
at91_rtc f80480b0.rtc: AT91 Real Time Clock driver.
i2c /dev entries driver
IR NEC protocol handler initialized
IR RC5(x/sz) protocol handler initialized
IR RC6 protocol handler initialized
IR JVC protocol handler initialized
IR Sony protocol handler initialized
IR SANYO protocol handler initialized
IR Sharp protocol handler initialized
IR MCE Keyboard/mouse protocol handler initialized
IR XMP protocol handler initialized
AT91: Starting after user reset
sama5d4_wdt f8048040.watchdog: initialized (timeout = 16 sec, nowayout = 0)
sdhci: Secure Digital Host Controller Interface driver
sdhci: Copyright(c) Pierre Ossman
sdhci-pltfm: SDHCI platform and OF driver helper
sdhci-at91 a0000000.sdio-host: update clk mul to 39 as gck rate is 480000000 Hz
mmc0: SDHCI controller on a0000000.sdio-host [a0000000.sdio-host] using ADMA
sdhci-at91 b0000000.sdio-host: update clk mul to 39 as gck rate is 480000000 Hz
mmc0: new high speed SDHC card at address 0007
mmcblk0: mmc0:0007 SD32G 29.0 GiB
mmcblk0: p1 p2
mmc1: SDHCI controller on b0000000.sdio-host [b0000000.sdio-host] using ADMA
ledtrig-cpu: registered to indicate activity on CPUs
atmel_aes f002c000.aes: version: 0x500
atmel_aes f002c000.aes: Atmel AES - Using dma0chan0, dma0chan1 for DMA transfers
atmel_sha f0028000.sha: version: 0x510
atmel_sha f0028000.sha: using dma0chan2 for DMA transfers
atmel_sha f0028000.sha: Atmel SHA1/SHA256/SHA224/SHA384/SHA512
atmel_tdes fc044000.tdes: version: 0x703
atmel_tdes fc044000.tdes: using dma0chan3, dma0chan4 for DMA transfers
atmel_tdes fc044000.tdes: Atmel DES/TDES
ip_tables: (C) 2000-2006 Netfilter Core Team
NET: Registered protocol family 10
Segment Routing with IPv6
sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
NET: Registered protocol family 17
can: controller area network core (rev 20170425 abi 9)
NET: Registered protocol family 29
can: raw protocol (rev 20170425)
can: broadcast manager protocol (rev 20170425 t)
can: netlink gateway (rev 20170425) max_hops=1
at91_i2c f8028000.i2c: can't get DMA channel, continue without DMA support
at91_i2c f8028000.i2c: Using FIFO (16 data)
at24 3-0050: 256 byte 24c02 EEPROM, writable, 8 bytes/write
at91_i2c f8028000.i2c: AT91 i2c bus driver (hw version: 0x704).
at91_i2c fc028000.i2c: can't get DMA channel, continue without DMA support
at91_i2c fc028000.i2c: Using FIFO (16 data)
at91_i2c fc028000.i2c: AT91 i2c bus driver (hw version: 0x704).
input: gpio_keys as /devices/platform/gpio_keys/input/input0
at91_rtc f80480b0.rtc: setting system clock to 2018-10-11 19:54:43 UTC (1539287683)
ALSA device list:
  #0: Dummy 1
atmel_usart_serial atmel_usart_serial.0.auto: using dma0chan5 for rx DMA transfers
atmel_usart_serial atmel_usart_serial.0.auto: using dma0chan6 for tx DMA transfers
random: fast init done
EXT4-fs (mmcblk0p2): recovery complete
EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
VFS: Mounted root (ext4 filesystem) on device 179:2.
devtmpfs: mounted
Freeing unused kernel memory: 1024K
EXT4-fs (mmcblk0p2): re-mounted. Opts: data=ordered
Starting logging: OK
Populating /dev using udev: udevd[111]: starting version 3.2.5
random: udevd: uninitialized urandom read (16 bytes read)
random: udevd: uninitialized urandom read (16 bytes read)
random: udevd: uninitialized urandom read (16 bytes read)
udevd[112]: starting eudev-3.2.5
atmel_usba_udc 300000.gadget: MMIO registers at [mem 0xfc02c000-0xfc02c3ff] mapped at c8a20000
atmel_usba_udc 300000.gadget: FIFO at [mem 0x00300000-0x003fffff] mapped at c8d00000
OF: graph: no port node found in /ahb/apb/isc@f0008000
atmel_isc f0008000.isc: no subdev found
done
Initializing random number generator... random: dd: uninitialized urandom read (512 bytes read)
done.
Starting system message bus: random: dbus-uuidgen: uninitialized urandom read (12 bytes read)
random: dbus-uuidgen: uninitialized urandom read (8 bytes read)
done
Starting network: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
udhcpc: started, v1.27.2
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending discover
udhcpc: no lease, failing
FAIL
Starting dropbear sshd: urandom_read: 2 callbacks suppressed
random: dropbear: uninitialized urandom read (32 bytes read)
OK
random: ssh-keygen: uninitialized urandom read (32 bytes read)
Starting sshd: OK
Starting Application Launcher: OK

Welcome to the Microchip Demo
sama5 login:

**Comment by TMScottSafety** [comment]
Hi Razvan,
I am using the linux4sam-poky-sama5d27_som1_ek_video-6.0.img
It cannot see the screen, see below:
Any idea where I should look?
Is the error related to a dead display?
Thank you,
Traian

“
…..
* Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon
random: avahi-daemon: uninitialized urandom read (4 bytes read)
random: avahi-daemon: uninitialized urandom read (4 bytes read)          [ ok ]
Starting crond: OK
cat: '/sys/class/drm/card0/*/modes': No such file or directory

Starting Demo...
OK

Poky (Yocto Project Reference Distro) 2.5.1 sama5d27-som1-ek-sd /dev/ttyS0

sama5d27-som1-ek-sd login: random: ApplicationLaun: uninitialized urandom read (4 bytes read)
Could not open DRM device /dev/dri/card0 (No such file or directory)
linuxfb: Failed to initialize screen


Poky (Yocto Project Reference Distro) 2.5.1 sama5d27-som1-ek-sd /dev/ttyS0
“

**Comment by RazvanStef** [comment]
Hello,
I tested the same image (ftp://www.at91.com/pub/demo/linux4sam_6.0/linux4sam-poky-sama5d27_som1_ek_video-6.0.img
[linux4sam-poky-sama5d27_som1_ek_video-6.0.img-bootlog.txt](https://github.com/linux4sam/meta-atmel/files/3328544/linux4sam-poky-sama5d27_som1_ek_video-6.0.img-bootlog.txt)
.bz2). From the logs you sent, you boot a buildroot image and there is no display detected at boot.

If u-boot detects the PDA, it should update the kernel bootargs as this:

> Kernel command line: console=ttyS0,115200 root=/dev/mmcblk0p2 rw rootfstype=ext4 rootwait atmel.pm_modes=standby,ulp1 video=Unknown-1:800x480-16

I've attached the bootlog for linux4sam-poky-sama5d27_som1_ek_video-6.0.img image.

Can you try with another screen? 

Regards,
Razvan

**Comment by ehristev** [comment]
Hello @TMScottSafety :
I am working on U-boot project and designed the detection.
Can you please stop the booting process in u-boot (when u-boot prints press any key to stop auto-boot).
and then issue 'printenv'
and let me know what is printed.
We can work out from there what is wrong with your setup.

As a side note, please be aware that U-boot automatically detects a screen and sets up for TM7000, TM7000B, TM5000 and TM4300.  If you screen is another flavor, but still compliant with detection, it will be detected and the 'pda' variable set accordingly. If your screen is not compliant with the detection then no detection will happen.
PDAs of 4.3" can be TM4300, TM4301, TM4301B etc.

**Comment by TMScottSafety** [comment]
Hi Eugen,
I have a display model TM4301B from  www.pdaatl.com<http://www.pdaatl.com>

Here is the ‘printenv’ output:

RomBOOT


AT91Bootstrap 3.8.11 (Thu Oct 11 17:16:10 UTC 2018)

SD/MMC: Image: Read file u-boot.bin to 0x23f00000
MMC: ADMA supported
SD: Card Capacity: High or Extended
SD: Specification Version 3.0X
SD/MMC: Done to load image
<debug_uart>

U-Boot 2018.07-linux4sam_6.0 (Oct 11 2018 - 17:16:11 +0000)

CPU: SAMA5D27 1G bits DDR2 SDRAM
Crystal frequency:       24 MHz
CPU clock        :      492 MHz
Master clock     :      164 MHz
DRAM:  128 MiB
MMC:   sdio-host@a0000000: 0, sdio-host@b0000000: 1
Loading Environment from FAT... OK
In:    serial@f8020000
Out:   serial@f8020000
Err:   serial@f8020000
Net:   eth0: ethernet@f8008000
Hit any key to stop autoboot:  0
=> printenv<INTERRUPT>
=> printenv
at91_pda_detect=run pda4300test; run pda7000test; run pda7000btest; run pda5000test;
at91_prepare_bootargs=test -n $display_var && setenv bootargs ${bootargs} ${at91_video_bootargs}
at91_prepare_overlays_config=test -n $display_var && setenv at91_overlays_config '#'${display_var}
at91_prepare_video_bootargs=test -n $display_var && setenv at91_video_bootargs video=${video_mode}
at91_set_display=test -n $pda && setenv display $pda
bootargs=console=ttyS0,115200 root=/dev/mmcblk0p2 rw rootfstype=ext4 rootwait atmel.pm_modes=standby,ulp1
bootcmd=run at91_set_display; run at91_pda_detect; run at91_prepare_video_bootargs; run at91_prepare_bootargs; run at91_prepare_overlays_config; run bootcmd_boot;
bootcmd_boot=fatload mmc 0:1 0x24000000 sama5d27_som1_ek.itb; bootm 0x24000000#kernel_dtb${at91_overlays_config}
bootdelay=1
ethact=gmac0
ethaddr=80:1f:12:41:73:ca
fdtcontroladdr=27b56488
pda=4301B
pda4300test=test -n $display && test $display = 4300 && setenv display_var 'pda4' && setenv video_mode ${video_mode_pda4}
pda5000test=test -n $display && test $display = 5000 && setenv display_var 'pda5' && setenv video_mode ${video_mode_pda5}
pda7000btest=test -n $display && test $display = 7000B && setenv display_var 'pda7b' && setenv video_mode ${video_mode_pda7b}
pda7000test=test -n $display && test $display = 7000 && setenv display_var 'pda7' && setenv video_mode ${video_mode_pda7}
stderr=serial@f8020000
stdin=serial@f8020000
stdout=serial@f8020000
video_mode_pda4=Unknown-1:480x272-16
video_mode_pda5=Unknown-1:800x480-16
video_mode_pda7=Unknown-1:800x480-16
video_mode_pda7b=Unknown-1:800x480-16

Environment size: 1658/16380 bytes
=>

**Comment by ehristev** [comment]
I see you have a special flavor of the 4300 PDA.

U-boot only checks for the 4300 display.
You can alter this configuration like this
=> edit pda4300test

then edit the line and make it look like this : 
test -n $display && test $display = 4301B && setenv display_var 'pda4' && setenv video_mode ${video_mode_pda4}

and press enter
and then 
=> saveenv
to save your changes

Notice that the only change is the replacement of '4300' with '4301B' (exactly the value of 'pda' , which is your detected screen ).

Let me know if this works

**Comment by noglitch** [comment]
One information displayed here: http://www.at91.com/linux4sam/bin/view/Linux4SAM/SelectingPDAatBoot#Practical_example_with_TM4301B_s

**Comment by TMScottSafety** [comment]
Thank you,
That is what I needed,
Traian
