### ISSUE TITLE
warrior branch

### ISSUE THREAD

**Issue by texierp** [linux4sam/meta-atmel#140]
Hi @RazvanStef,

Are there any plans to release a warrior branch ?
It would be nice :) 

BR

/Pierre-Jean

**Comment by RazvanStef** [comment]
Hello @texierp ,

We are currently working on a Linux4SAM release based on thud branch. After that is done, we will continue with a warrior branch.

Master branch has support for warrior. if you like to try it.

Best regards,
Razvan

**Comment by texierp** [comment]
Hello,

> We are currently working on a Linux4SAM release based on thud branch. After that is done, we will continue with a warrior branch.

Ok, I understand, thanks for the clarification.

> Master branch has support for warrior. if you like to try it.

Already tested in fact, it's just to have the same branches on my repo, but I can wait, for sure ;).

BR
/Pierre-Jean

**Comment by RazvanStef** [comment]
I can add a warrior branch to the repo, for development, if it makes it easier for you. But testing on it is going to be minimal for the moment.

Regards,
Razvan

**Comment by texierp** [comment]
Many thanks @RazvanStef
