### ISSUE TITLE
Build issue with QtWebEngine

### ISSUE THREAD

**Issue by RazvanStef** [linux4sam/meta-atmel#144]
Hi Razvan,

Thanks for letting me know.  I have taken the files from the thud branch and replaced the ones in my working directory and QtBase now builds correctly.

I have found another build issue with QtWebEngine.  Looking in the log files directory it seems as though the only error I can see is in log.do_configure:

khronos development headers appear to be missing (mesa/libegl1-mesa-dev)
QtWebEngine will not be built.

Is this there another patch I need to cherrypick from thud to fix this?

-Andy.

_Originally posted by @andy-sdc in https://github.com/linux4sam/meta-atmel/issues/142#issuecomment-513726162_

**Comment by noglitch** [comment]
We don't plan to maintain QtWebEngine anymore neither to investigate this issue. Sorry about that.
Best regards,
  Nicolas
