### ISSUE TITLE
Control a LED with BUTTON on SAMA5D27-SOM1-EK1 board

### ISSUE THREAD

**Issue by gastonso** [linux4sam/meta-atmel#145]
Hello!

I think that my question is a little bit dumb but i am really stuck in this problem. I have an embedded **SAMA5D27-SOM1-EK1** board which i build **Linux** OS image version 4.14 with **YOCTO** project. Now i want to control a RBG **LED** ( one of the three existing in the shematics of the board ) using a push **USER BUTTON** existing both on the board. I must make the LED Lights when I push the Button. For the moment i have only the PINS of the Led and the Button. I don't know what i must do now. But i think that i must modify dts file. I don't know how.

Thank you for your help!

**Comment by noglitch** [comment]
Sorry but it's not the proper location for asking such questions. This discussion is for dealing with issues concerning the meta-atmel YP layer.
I advice you to use the at91.com forum for discussing this and in parallel learn about the LED Linux sub-system.
I then close this issue. Best regards, Nicolas.
