### ISSUE TITLE
Is angstrom-sdk and arm sdk necessary for at91sam9m10 compilation?

### ISSUE THREAD

**Issue by fberndl** [linux4sam/meta-atmel#161]
Hi, 

in older versions of u-boot the angstrom-sdk ( for compiling u-boot) and arm sdk ( for compiling bootstrap) was needed if I understood it correctly. 

I did not find any depenency to this sdk's so they are not needed anymore using current yocto releases?

SOC: at91sam9m10

**Comment by codrin989** [comment]
I don't know about angstrom or arm sdks, but you can find the dependencies by typing 'bitbake -g <packet_name>' and investigating the recipe-depends.dot file. Do you have issues compiling u-boot/at91bootstrap for at91sam9m10?

**Comment by fberndl** [comment]
Hi,

it seems that angstrom and arm sdks are quite old. before yocto/poky had in-built support of it. So it should not be needed anymore.
