### ISSUE TITLE
Remove dtc 1.4.x recipe

### ISSUE THREAD

**Issue by kraj** [linux4sam/meta-atmel#167]
I see this layer is housing an older version of dtc 1.4.x than core (OE-Core 1.5.x ), this causes problems due to this layer having higher priority this one gets picked up. So I would like to ask

1. Do we still need to use dtc 1.4.x in meta-atmel ? if no then delete it
2. If we need to use it for some reason, then lets rename it to something like dtc-145.bb and convert all references to use that PN inside this layer, so this does not spread around t other layers in multi-BSP setup.

I can cook up the patch, I just need to know the above two points

**Comment by codrin989** [comment]
I removed the dtc recipe. I hope everything is fine now. Thanks for reporting the issue.
