### ISSUE TITLE
Support for stm32mp157c-dk2

### ISSUE THREAD

**Issue by nandra** [linux4sam/meta-atmel#170]
Hi,

this is not really an issue but question if this board : https://www.arrow.com/en/products/stm32mp157c-dk2/stmicroelectronics is supported by this layer. Thanks.

**Comment by alexandrebelloni** [comment]
Hello,

I'm not sure why you would think Microchip would support a board based on an ST Microelectronics SoC. meta-atmel doesn't support this board but meta-st-stm32mp does: https://github.com/STMicroelectronics/meta-st-stm32mp

**Comment by nandra** [comment]
@alexandrebelloni oh sorry ;). Thanks for info.
