### ISSUE TITLE
I'm using a file system compiled from a recipe, and I get errors running egt-launche program.

### ISSUE THREAD

**Issue by blithe2015** [linux4sam/meta-atmel#188]
root@NECRO:~# egt-launcher 
terminate called after throwing an instance of 'std::runtime_error'
  what():  unable to open DRM driver
Aborted (core dumped)

Does this error occur because drm is not supported?

**Comment by ldesroches** [comment]
Hi,

No it doesn't mean that DRM is not supported, it means that it can't open the driver so it's probably missing. Maybe the overlay for the screen is not loaded preventing the probe of the LCD driver.

Ludovic

**Comment by noglitch** [comment]
Hi @blithe2015 , can we have more info about the platform? LCD used? Yocto Project image generated?

**Comment by blithe2015** [comment]
> platform
The platform is STM32MP157. LCD is used,the image is Successful.

**Comment by noglitch** [comment]
Probably components missing on this platform. Works well on all our SoCs. I close it.
