### ISSUE TITLE
Secure Boot suppot for SAMA5D2

### ISSUE THREAD

**Issue by Noufalp90** [linux4sam/meta-atmel#202]
Hi Team,

Does the meta-atmel support secure boot on SAMA5D2?

Regards
Noufal P

**Comment by codrin989** [comment]
Hi @Noufalp90 . There is an article here https://connect.ed-diamond.com/GNU-Linux-Magazine/GLMF-221/U-Boot-a-la-decouverte-du-demarrage-verifie made by @texierp . with some steps on how to enable secure boot on SAMA5D27-SOM1 with meta-atmel. Hope it helps.

**Comment by Noufalp90** [comment]
It supports English? am getting it in another language. 
+ Is it possible to build image using yocto for secure boot?

**Comment by codrin989** [comment]
meta-atmel does not generate secure boot images out-of-the-box. You could take a look at @texierp  's fork https://github.com/texierp/meta-atmel and see whether it includes any changes for secure boot.

**Comment by Noufalp90** [comment]
Okay. So using buildtroot is required for secure boot support. Correct me  if am wrong.

**Comment by codrin989** [comment]
buildroot is in the same situation as meta-atmel. The buildroot images are similar with the meta-atmel ones.

**Comment by Noufalp90** [comment]
Okay. Even with yocto also, secure boot is possible?

**Comment by codrin989** [comment]
secure boot is not restricted to a certain build system. I provided you above with a link to an article that explains very nicely how to do this with meta-atmel. Even if it's in french, I am sure you can find an easy way to translate it. There is also [this](http://ww1.microchip.com/downloads/en/AppNotes/DS00002748A.pdf) application note that uses buildroot and shows what changes are needed for secure boot. If you have other questions, please make a [support ticket](https://microchipsupport.force.com/s/). Thanks!
