### ISSUE TITLE
Non GUI Image for SAM9X60 

### ISSUE THREAD

**Issue by ankitsingh1508** [linux4sam/meta-atmel#218]
Hi,

Tried "microchip-graphics-image" for SAM9X60 and it boots and works fine with GUI display but when tried other images like "core-image-minimal" then nothing comes on screen (i was expecting linux terminal login screen).
Am i missing some thing to be added to local.conf for this...?

Regards.

**Comment by mattwood-microchip** [comment]
Core-image-minimal is a console image target with stdio on a USART connected to the virtual com port on the onboard jlink debugger (J22).  If you really want to redirect to the display you need to enable the fbcon driver and update the kernel command line boot args.  You can Google more about it or reference the kernel docs below.
https://docs.kernel.org/fb/fbcon.html

**Comment by ankitsingh1508** [comment]
@mattwood-microchip 
Thanks a lot for the guidance.
