### ISSUE TITLE
linux-mchp_6.6

### ISSUE THREAD

**Issue by hevandpatel** [linux4sam/meta-atmel#273]
| rm: cannot remove '/home/Projects-local/icm4-yocto/poky/build-microchip/tmp/work/sama5d2_xplained_sd-poky-linux-gnueabi/linux-mchp/6.6+git999-r0/image/lib/modules/6.6.23-linux4microchip-2024.04-rc1+/source': No such file or directory
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/Projects-local/icm4-yocto/poky/../meta-atmel/recipes-kernel/linux/linux-mchp_6.6.bb:do_install) failed with exit code '1'

**Comment by ylin-witekio** [comment]
Experiencing the same issue here. Does anyone have a work around?

**Comment by Dharma-B** [comment]
Hi,
You should update the poky layer to tag:4.0.17, this resolves your issue.
