### ISSUE TITLE
Update to Scarthgap

### ISSUE THREAD

**Issue by fsimon-mertens** [linux4sam/meta-atmel#275]
Are there already plans to upgrade to Yocto Version Scarthgap? Is there already a time frame determined?

**Comment by gehariprasath** [comment]
Hi,

Our next Linux4Sam 2024.10 release will be based on 'Scarthgap' scheduled to release end of October. Meanwhile we have pushed the current scarthgap branch, but pls note that it's a work in progress and not extensively tested. You can play with it and let us know if you face any issues. We will be glad to fix it.

Regards,
Hari
