### ISSUE TITLE
Meta-Atmel not working for SAMA5D3XEK

### ISSUE THREAD

**Issue by Jhaerirg** [linux4sam/meta-atmel#36]
The next recipe fails in the process  to generate core-image-minimal:
../meta-atmel/recipes-kernel/linux/linux-yocto-custom_3.10.bb, do_compile failed with exit code '1', in specific with:
../linux/arch/arm/mach-at91/sleep_sama5.S: Assembler messages:
23: Error: cannot use register index with PC-relative addressing -- `str r0,.saved_lpr'

I followed the procedure indicated in the README for target sama5d3xek.

**Comment by gizero** [comment]
Just opened PR #37 which also works this around by pointing SRCREV to a commit before the offending one.
