### ISSUE TITLE
please add meta-atmel to the OE metadata index

### ISSUE THREAD

**Issue by twoerner** [linux4sam/meta-atmel#49]
Hi,

Would you be interested in adding your meta-atmel layer to the OpenEmbedded Metadata Index? It make it easier for others to find your work!

http://layers.openembedded.org/layerindex/branch/master/layers/
http://layers.openembedded.org/layerindex/submit/

Best regards,
   Trevor

**Comment by noglitch** [comment]
Indeed I'd love it.
In fact I'm heading for it for years but always find the layer not in good shape enough to take the plunge...

**Comment by noglitch** [comment]
I've just done it... let's wait for its review by the moderator.

**Comment by twoerner** [comment]
Awesome!! I can see that it has shown up in the index:
http://layers.openembedded.org/layerindex/branch/master/layer/meta-atmel/

Thanks :-)

**Comment by noglitch** [comment]
Yes, I'm happy it does! Thanks, bye.
