### ISSUE TITLE
Automated generation of u-boot environment files

### ISSUE THREAD

**Issue by mikolajpp** [linux4sam/meta-atmel#55]
I would like to discuss a feature I am interested in implementing: automated generation of u-boot environment binary files, similar to https://github.com/koenkooi/meta-edison/blob/master/recipes-bsp/u-boot/u-boot-target-env.inc

There are at least two options to go about this:
- The same as in meta-edison layer, that is, u-boot recipe sources file defining commands which generate u-boot environment files
- Separate recipe file, say "u-boot-env-gen", which would handle solely environment generation.

I would prefer to go the first way, as logically this should be part of u-boot recipe, the same as kernel recipes handle device tree compilation.

**Comment by RazvanStef** [comment]
Patches added to master branch:
ca40be3 u-boot-at91: Generate release u-boot environment razvan.stefanescu@microchip.com 
6f126bc u-boot-at91: Add environment to u-boot-at91_2018.07 razvan.stefanescu@microchip.com 
ce43196 machine: Add uboot.env to wic image razvan.stefanescu@microchip.com 

Will be included in linux4sam_6.1 release.
