### ISSUE TITLE
watchdog at bootstrap is enabled and interrupts the boot process

### ISSUE THREAD

**Issue by StefJar** [linux4sam/meta-atmel#87]
It depends on the size of the kernel & u-boot. But it is possible that the watchdog is firing before the kernel driver is loaded.
setting the .config file for bootstrap to
`CONFIG_DISABLE_WATCHDOG=y`
helps to overcome this problem.

**Comment by noglitch** [comment]
Hi,
In Config.in the default is "yes" for the value "CONFIG_DISABLE_WATCHDOG". As no defconfig of AT91Bootstrap unset this variable, CONFIG_DISABLE_WATCHDOG=y is present by default in the .config when compiling AT91Bootstrap for all platforms.
So, I suspect that what you propose is already implemented.
Regards,
