### ISSUE TITLE
How to correctly modify kernel configuration?

### ISSUE THREAD

**Issue by logictom** [linux4sam/meta-atmel#88]
I'll start out by saying I know this may not be the correct place for this question but I am unable to log into the at91.com message board to post this question - waiting on response from webmaster@at91.com to resolve this. If there is an alternative area I can post this then please let me know.

I am using the SAMA5D2-xplained demo board, as a first step I simply want to enable btrfs. Working through a book I have (and looking at a couple of tutorials) they use config fragments but after much trial an error I have realised that for this to work requires that the linux-at91_4.9.bb has to require linux-yocto for this to work.
I have tried adding my own defconfig inside my layer and including this with an appropriate SRC_URI but, even though my layer has a higher priority, I can't get yocto to include my defconfig instead of the meta-atmel one.

Couple of questions:
What is the correct way to alter the meta-atmel configuration using my own layer? I don't know at this stage if I am just barking up the wrong tree or if there is an issue somewhere.
What is the reason behind the linux-at91_4.9.bb only requiring the dtb and not the entire linux-yocto, which would allow the use of fragments?

**Comment by RazvanStef** [comment]
Hello,
Have you tried creating a .bbappend and adding your defconfig to SRC_URI?

Regards,
Razvan
