### ISSUE TITLE
How to add new packages and libraries from a the demo image

### ISSUE THREAD

**Issue by AnneNJ** [linux4sam/meta-atmel#89]
Hi everyone,

I am using a SAMA5D2 board.

I was wondering how I can add additionnal packages and functionnalities to my board. Since the demo Image provides a very basic version of Linux. The only package manager I have is opkg and there is no Atmel opkg repository specified in opkg.conf

Has someone ever tried something like this?

Thanks in adavance for your help.

Anne

**Comment by noglitch** [comment]
Answer in AT91Bootstrap same issue issue.
