### ISSUE TITLE
nano.specs support

### ISSUE THREAD

**Issue by hot-dog2017** [linux4sam/meta-atmel#91]
Hi,

Im trying to re-compile binaries for SAM-BA using the Cross compiler exposed by Yocto (Krogoth).

Ive found that there is no support for nano.specs. Is this support to be added for Atmel targets?

Ive downloaded example recipes for "newlib" ie https://github.com/jurobystricky/meta-zephyr/tree/master/recipes-core/newlib

Id like to use the CC generated by Yocto rather that the downloaded version. Could someone help please.

Thanking you in advance..

**Comment by alexandrebelloni** [comment]
OE/Yocto doesn't have any support to generate a newlib based toolchain and use it to generate a linux image.

What you are pointing to is a fork of meta-zephyr which is actually a layer used to buld an SDK for zephyr (not Linux).

**Comment by hot-dog2017** [comment]
Your correct, the meta-zephr newlib support ive already tried to incorporate into my SDK but failed to.

There is very little on adding support for newlib. Is there any info / examples someone help with?..

**Comment by alexandrebelloni** [comment]
oe-core only has support for glibc and musl. I don't think anybody has added support for newlib.

**Comment by hot-dog2017** [comment]
..does body know how i would add newlib support?
