### ISSUE TITLE
https://github.com/linux4sc/wireless-driver no longer available

### ISSUE THREAD

**Issue by mnsgs** [linux4sam/meta-atmel#92]
Hi,

linux4sc seems removed from Github. What is the story behind it and how do we mitigate it?

**Comment by alexandrebelloni** [comment]
I think the firmwares made it to linux-firmware so that is what you can use instead of atmel-wireless-firmware if you need it. Else just drop the recipe.

**Comment by noglitch** [comment]
Yes this github has been closed (without previous notice).
So I removed the recipe. Please go to https://github.com/linux4wilc/ for more information.
Best regards
