### ISSUE TITLE
atmel-wireless-firmware_git.bb has invalid repo

### ISSUE THREAD

**Issue by Plasmarobo** [linux4sam/meta-atmel#94]
The Dizzy Branch has an invalid recipe in it.
recipes-kernel/linux/atmel-wireless-firmware_git.bb fails to expand SRCPV with a "Repository not found." error.

We do not use this firmware in our build, but the failure halts the build process.
We can solve the issue by deleting the file, but a proper solution should be found.
(If the repo no longer exists perhaps a frozen zip of the firmware or a forked repo should be selected).

**Comment by noglitch** [comment]
now fixed with 196b7e02adaa2b4c83fb66b8a818775560d4db76
Best regards
